version: '3.6'

services:
    postgres:
        image: postgres:9.6-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=sqalx
            - POSTGRES_PASSWORD=sqalx

    mysql:
        image: mysql:8.0 # intel only
        # image: mysql/mysql-server:8.0 # mac M1 preview
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=sqalx
            - MYSQL_USER=sqalx
            - MYSQL_PASSWORD=sqalx
            - MYSQL_DATABASE=sqalx
